name: copernicus-training
channels:
  - conda-forge
dependencies:
  # Jupyter & Python
  - python=3.10
  - jupyterlab
  - ipykernel
  - ipywidgets
  - numpy
  - pandas
  - xarray
  - matplotlib
  - cartopy
  - datetime
  - copernicusmarine

  # R
  - r-base=4.3
  - r-irkernel
  - r-tidyverse
  - r-ggplot2
  - r-RColorBrewer
  - r-ncdf4
  - r-gridExtra
  - r-lubridate
  - r-scales
  - r-ggquiver
  - r-magick
  # add more R packages if needed
