name: copernicus-training
channels:
  - conda-forge
dependencies:
  # Python
  - python=3.10
  - pip
  - ipykernel
  - ipywidgets
  - numpy
  - scipy
  - matplotlib
  - xarray
  - rioxarray
  - geopandas
  - geoviews
  - hvplot
  - netcdf4
  - cmocean
  - copernicusmarine
  - jupyterlab

  # R
  - r-base=4.3
  - r-irkernel
  - r-tidyverse
  # add more R packages if needed
