name: copernicus-training
channels:
  - conda-forge
dependencies:

  - python=3.11
  - jupyterlab
  - notebook<7

  - numpy
  - pandas
  - xarray
  - matplotlib
  - cartopy          
  - copernicusmarine 


  - r-base
  - r-irkernel


  - r-ggplot2
  - r-dplyr
  - r-rcolorbrewer
  - r-ncdf4      
  - r-gridextra
  - r-lubridate
  - r-scales     
  - r-magick   
